# docker-compose.yaml
name: low-latency-observability
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - grafana-data:/var/lib/grafana
      - ../../observability/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ../../observability/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ../../observability/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../../observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../../observability/prometheus/rules.yml:/etc/prometheus/rules.yml
    ports:
    - "9090:9090"

  low-latency-app:
    build: 
      context: ../..
      dockerfile: build/Dockerfile
    image: ghcr.io/rysekk/low-latency-app:0.2
    container_name: low-latency-app
    restart: unless-stopped
    ports:
    - "8080:8080"

volumes:
  grafana-data:
