apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provider
  namespace: trading-app
data:
  provider.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        options:
          path: /var/lib/grafana/dashboards