apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: trading-app
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus.trading-app:9090
        isDefault: true