name: CI

on:
  push:
    branches: [main]      # On witch branch

jobs:
  lintAndTest:
    runs-on: ubuntu-24.04
    
    steps:
      - uses: actions/checkout@v7        # Get codebase

      - uses: actions/setup-go@v7        # instal Go
        with:
          go-version: '1.26.5'          
      
      - name: lint                       # Lint
        run: go vet ./...
      
      - name: Run tests
        run: go test ./...               # test
  
  
  build-push:
    needs: lintAndTest
    runs-on: ubuntu-24.04
    
    permissions:
      packages: write
      contents: write

    steps:
      - name: Login to Github pkgs
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/checkout@v7
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./build/Dockerfile
          push: true
          tags: ghcr.io/rysekk/low-latency-observability:${{ github.sha }}
      
      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          
          yq -i ".spec.template.spec.containers[0].image = \
          \"ghcr.io/rysekk/low-latency-observability:${{ github.sha }}\"" \
          deploy/app/deployment.yaml

          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add deploy/k8s/app/deployment.yaml

          git checkout main
          
          git commit -m "chore: update image to tag ${{ github.sha }} [skip ci]" || echo "No changes to commit"
          
          git push origin main


      