name: CI

on:
  push:
    branches: [main]      # sur quelle branche ?

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4        # récupère ton code sur la machine

      - uses: actions/setup-go@v5        # installe Go
        with:
          go-version: '1.26.5'              # quelle version ? regarde ton go.mod

      - name: Run tests
        run: cd cmd/ingestor && go test                       # la commande qui lance tes tests